name: Check links in Markdown files
on:
  schedule:
    - cron: 0 0 * * 1 # midnight every Monday
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: yes
          use-verbose-mode: yes
          folder-path: "_episodes, _extras, _includes"
          file-path: "./README.md, ./LICENSE, ./CODE_OF_CONDUCT.md, CONTRIBUTING.md, reference.md, setup.md, index.md"
